//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3_MVC2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Agriculture_DatabaseEntities : DbContext
    {
        public Agriculture_DatabaseEntities()
            : base("name=Agriculture_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agri_Products> Agri_Products { get; set; }
        public virtual DbSet<Apple> Apples { get; set; }
        public virtual DbSet<Apricot> Apricots { get; set; }
        public virtual DbSet<Blueberry> Blueberries { get; set; }
        public virtual DbSet<Fruit> Fruits { get; set; }
        public virtual DbSet<Mushroom> Mushrooms { get; set; }
        public virtual DbSet<Potato> Potatoes { get; set; }
        public virtual DbSet<Tomato> Tomatoes { get; set; }
        public virtual DbSet<Vegetable> Vegetables { get; set; }
    }
}
